    
    // <auto-generated />
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Metadata;

    #pragma warning disable 219, 612, 618
    #nullable disable

    namespace CompiledModelsExample
    {
        [DbContext(typeof(ExampleContext))]
        public partial class ExampleContextModel : RuntimeModel
        {
            static ExampleContextModel()
            {
                var model = new ExampleContextModel();
                model.Initialize();
                model.Customize();
                _instance = model;
            }

            private static ExampleContextModel _instance;
            public static IModel Instance => _instance;

            partial void Initialize();

            partial void Customize();
        }
    }

