
    // <auto-generated />
    using System;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Metadata;

    #pragma warning disable 219, 612, 618
    #nullable disable

    namespace CompiledModelsExample
    {
        public partial class ExampleContextModel
        {
            partial void Initialize()
            {
                var person = PersonEntityType.Create(this);

                PersonEntityType.CreateAnnotations(person);

                AddAnnotation("ProductVersion", "6.0.0");
                AddAnnotation("Relational:MaxIdentifierLength", 128);
                AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
            }
        }
    }

